### ISSUE TITLE
Error when Fog.mock! enabled

### ISSUE THREAD

**Issue by benburkert** [lstoll/fog-octocloud#3]
Here's the stacktrace from the rspec run:

```
Failures:

  1) Enterprise::Toolchain::Apt::Setup octocloud can provision a server in mocked mode
     Failure/Error: subject.call(payload.merge('block' => block))
     NoMethodError:
       undefined method `local_mode' for #<Fog::Compute::Octocloud::Mock:0x007ff41fc34d10>
     # ./vendor/gems/ruby/1.9.1/bundler/gems/fog-octocloud-e0662a65a5e6/lib/fog/octocloud/models/compute/servers.rb:43:in `model'
     # ./vendor/gems/ruby/1.9.1/bundler/gems/fog-2ab2111a2ede/lib/fog/core/collection.rb:116:in `new'
     # ./vendor/gems/ruby/1.9.1/bundler/gems/fog-2ab2111a2ede/lib/fog/core/collection.rb:51:in `create'
     # ./lib/enterprise/toolchain/conduits/compute/provision.rb:36:in `run'
     # ./lib/enterprise/toolchain/conduit.rb:117:in `call_internal'
     # ./lib/enterprise/toolchain/conduit.rb:107:in `call'
     # ./lib/enterprise/toolchain/conduit.rb:108:in `block in call'
     # ./lib/enterprise/toolchain/conduit.rb:118:in `call'
     # ./lib/enterprise/toolchain/conduit.rb:118:in `call_internal'
     # ./lib/enterprise/toolchain/conduit.rb:107:in `call'
     # ./lib/enterprise/toolchain/pipeline.rb:20:in `call'
     # ./spec/unit/conduits/compute/provision_spec.rb:53:in `block (3 levels) in <top (required)>'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:114:in `instance_eval'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:114:in `block in run'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:179:in `call'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:179:in `run'
     # ./spec/unit/conduits/compute/provision_spec.rb:21:in `block (2 levels) in <top (required)>'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/extensions/instance_eval_with_args.rb:16:in `instance_exec'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/extensions/instance_eval_with_args.rb:16:in `instance_eval_with_args'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:247:in `instance_eval_with_args'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/hooks.rb:87:in `block (2 levels) in run'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/hooks.rb:85:in `call'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/hooks.rb:85:in `run'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/hooks.rb:418:in `run_hook'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:329:in `run_around_each_hooks'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:256:in `with_around_each_hooks'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:111:in `run'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:390:in `block in run_examples'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:386:in `map'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:386:in `run_examples'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:371:in `run'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:372:in `block in run'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:372:in `map'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:372:in `run'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:28:in `map'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:28:in `block in run'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/reporter.rb:34:in `report'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:25:in `run'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/runner.rb:80:in `run'
     # ./vendor/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/runner.rb:17:in `block in autorun'
```
